# <center>Laboratorium 1<br>Metody Numeryczne</center>

Biblioteki niezbędne do wykonania zadania:

(wykonanie tego bloku zapewnia do nich dostęp w kolejnych blokach)

In [26]:
import main

import math
import numpy as np
import scipy

Przydatne w trakcie zajęć mogą okazać się metody macierzy z pakietu Numpy, takie jak na przykład długość wektora - *[len]()* czy rozmiar macierzy -
*[shape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html#numpy.ndarray.shape)*. Poniższy kod ilustruje ich podstawowe działanie. Dodatkowe metody obiektu $ndarray$ można znaleźć w oficjalnej *[dokumentacji](https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html)*.

In [27]:
vector = np.array([1, 2, 3])
print('Wektor:')
print(vector)
print('Długość:', len(vector))
print('Rozmiar:', vector.shape, '\n')

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('Macierz:')
print(matrix)
print('Rozmiar:', matrix.shape)

Wektor:
[1 2 3]
Długość: 3
Rozmiar: (3,) 

Macierz:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Rozmiar: (3, 3)


***Zadanie 1.***  
Zaimplementuj funkcję $cylinder\_area$ tak by zwracała pole powierzchni walca o promieniu podstawy $r$ i wysokości $h$. Stała $\pi$ jest zdefiniowana np. w bibliotece *[math](https://docs.python.org/3/library/math.html#constants)*. Jeżeli nie da się policzyć pola funkcja powinna zwracać wartość *NaN*. Sprawdź działanie zaimplementowanej funkcji dla dowolnych wartości w tym notatniku.


In [28]:
def cylinder_area(r:float,h:float):
    """Obliczenie pola powierzchni walca. 
    Szczegółowy opis w zadaniu 1.
    
    Parameters:
    r (float): promień podstawy walca 
    h (float): wysokosć walca
    
    Returns:
    float: pole powierzchni walca 
    """
    if r <= 0 or h <= 0:
        return math.nan
    else:
        pp:float = 2*math.pi*r*r
        pb:float = 2*math.pi*r*h
        return pp+pb
cylinder_area(5, 5)

314.1592653589793

***Zadanie 2.***  
Wygeneruj dowolne ciągi arytmetyczny o kroku różnym od jeden i niebędącym liczbą całkowitą, używając w tym celu funkcji *[arange](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html)* oraz *[linspace](https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.linspace.html)*. Wypisz go i przeanalizuj otrzymane rezultaty.

In [29]:
print('1 = ' , np.linspace(0.1, 0.99, num=10))
print('2 = ' , np.arange(0.1,0.99,0.05))

1 =  [0.1        0.19888889 0.29777778 0.39666667 0.49555556 0.59444444
 0.69333333 0.79222222 0.89111111 0.99      ]
2 =  [0.1  0.15 0.2  0.25 0.3  0.35 0.4  0.45 0.5  0.55 0.6  0.65 0.7  0.75
 0.8  0.85 0.9  0.95]


***Zadanie 3.***  
Zaimplementuj funkcję $fib$ zwracającą wektor pierszych n elementów *[ciągu Fibonnaciego](https://pl.wikipedia.org/wiki/Ci%C4%85g_Fibonacciego)*, jeżeli nie jest to możliwe funkcja powinna zwrócić wartość *None*.

In [30]:
def fib(n:int):
    """Obliczenie pierwszych n wyrazów ciągu Fibonnaciego. 
    Szczegółowy opis w zadaniu 3.
    
    Parameters:
    n (int): liczba określająca ilość wyrazów ciągu do obliczenia 
    
    Returns:
    np.ndarray: wektor n pierwszych wyrazów ciągu Fibonnaciego.
    """
    if n <= 0:
        return None
    if not isinstance(n, int):
        return None
    if n == 1:
        return 1
    else:
        i, first, second = 0, 0, 1
        fibonacci = []
        while i < n:
            first, second = second, first + second
            fibonacci.append(first)
            i = i + 1            
        return [fibonacci]

fib(12)

[[1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144]]

***Zadanie 4.***  
Napisz funkję $matrix\_calculations$ która jako argument przyjmuje dowolną wartość liczbową *a* i tworzy macierz:  
  
$\mathbf{M} =\left[ \begin{matrix}
a & 1 & -a\\
0 & 1 & 1\\
-a & a & 1
\end{matrix}\right]
$    
   
Dla zadeklarowanej macierzy wyznacz numerycznie macierz odwrotną $\mathbf{Minv}$ (jeżeli nie istnieje taka macierz wartość wynosi NaN), macierz transponowaną $\mathbf{Mt}$ i wyznacznik macierzy $\mathbf{Mdet}$. Zwróć otrzymane wartości w postaci krotki postaci $(\mathbf{Minv}, \mathbf{Mt}, \mathbf{Mdet})$.  Wypisz otrzymane wyniki. 
  
***Wskazówki:*** Do tworzenia obiektów mających własności macierzy w języku Python używa się klasy *[array](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.array.html)* z pakietu *[numpy](http://www.numpy.org/)*, przykładowe użycie:

In [31]:
import numpy as np # słowo kluczowe "as" oznacza przesłania nazwę numpy i pozwala  
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
A = np.array([[1,2],[3,4]])
print("Wektor poziomy:\n {0}".format(a))
print("Wektor pionowy:\n {0}".format(b))
print("Macierz:\n {0}".format(A))

Wektor poziomy:
 [1 2 3]
Wektor pionowy:
 [[1]
 [2]
 [3]]
Macierz:
 [[1 2]
 [3 4]]


Do wykonania operacji odwracania macierzy należy użyć funkcji *[inv](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html)*, do obliczenia wyznacznika macierzy stosuje się funkcję *[det](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.linalg.det.html)*  z bliblioteki *[linalg](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)*. Natomiast transpozycję macierzy wykonujemy przez funkcję *[transpose](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.transpose.html)* której skrucona wersja to $M.T$ z pakietu *numpy*.  
    
*Ciekawostka:* Python natywnie nie zawiera struktury danych typu tablica, na poziomie języka jest to rozwiązane poprzez strukturę listy list do której elementów odwołuje się poprzez indeksy jak w C/C++.


Rozwiązanie:

In [32]:
def matrix_calculations(a: float):
    """Funkcja zwraca wartości obliczeń na macierzy stworzonej 
    na podstawie parametru a.  
    Szczegółowy opis w zadaniu 4.
    
    Parameters:
    a (float): wartość liczbowa 
    
    Returns:
    touple: krotka zawierająca wyniki obliczeń 
    (Minv, Mt, Mdet) - opis parametrów w zadaniu 4.
    """
    M = np.array([[a, 1, -a], [0, 1, 1], [-a, a, 1]])
    if a == 0:
        Minv = math.nan
    else:
        Minv = np.linalg.inv(M)
    Mt = np.transpose(M)
    Mdet = np.linalg.det(M)
    result = (Minv, Mt, Mdet)
    return result

matrix_calculations(1)

(array([[ 0. ,  1. , -1. ],
        [ 0.5,  0. ,  0.5],
        [-0.5,  1. , -0.5]]),
 array([[ 1,  0, -1],
        [ 1,  1,  1],
        [-1,  1,  1]]),
 -2.0)

***Zadanie 5.***  
Stwórz w noataniku macierz:  
$\mathbf{M} =\left[ \begin{matrix}
3 & 1 & -2 & 4\\
0 & 1 & 1 & 5\\
-2 & 1 & 1 & 6\\
4 & 3 & 0 & 1\\
\end{matrix}\right]
$   
Wypisz przy pomocy funkcji *print* następujące elementy macierzy $\mathbf{M}$: $\mathbf{M}_{1,1},\mathbf{M}_{3,3},\mathbf{M}_{3,2}$. Zdefiniuj wektor $\mathbf{w1}$ którego elementy to trzecia kolumna macierzy $\mathbf{M}$ oraz wektor $\mathbf{w2}$ który składa się z drugiego wiersza tej macierzy.  
  
***Wskazówki:***
Tablice z pakietu *numpy* są indeksowane od zera a do każdego elementu można odwołać się poprzez jego indeks. Przykład użycie


In [33]:
# Inicjalizacja macierzy do przykładu
P = np.array([[1,3,2],[3,4, 6],[7,8,9]])
print("Macierz P=\n{0}".format(P))
# wyciągnięcie trzeciej kolumny 
wektor1 = P[:,2]
# wyciągnięcie trzeciego wiersza 
wektor2 = P[2,:]
print("Elementy trzeciej kolumny:\n {0}".format(wektor1))
print("Elementy trzeciego wiersza:\n {0}".format(wektor2))

Macierz P=
[[1 3 2]
 [3 4 6]
 [7 8 9]]
Elementy trzeciej kolumny:
 [2 6 9]
Elementy trzeciego wiersza:
 [7 8 9]


Rozwiązanie:

In [34]:
M = np.array([[3, 1, -2, 4], [0, 1, 1, 5], [-2, 1, 1, 6], [4, 3, 0 ,1]])
print("Macierz M=\n{0}\n".format(M))
w1 = M[:,2]
print("Elementy trzeciej kolumny:\n {0}\n".format(w1))
w2 = M[1,:]
print("Elementy drugiego wiersza:\n {0}\n".format(w2))

print("M[1][1] =", M[0][0]) 
print("M[3][3] =", M[2][2]) 
print("M[3][2] =", M[2][1]) 

Macierz M=
[[ 3  1 -2  4]
 [ 0  1  1  5]
 [-2  1  1  6]
 [ 4  3  0  1]]

Elementy trzeciej kolumny:
 [-2  1  1  0]

Elementy drugiego wiersza:
 [0 1 1 5]

M[1][1] = 3
M[3][3] = 1
M[3][2] = 1


Dodatkowo twórcy biblioteki umożliwiają użytkownikowi na manipulację elementami tablicy poprzez operator ':', więcej szczegółów na temat jego użycia w artykule [NumPy for Matlab users](https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html#numpy-for-matlab-users).

***Zadanie 6.***   
Uzupełnij funkcję $custom\_matrix$, tak by parametry m, n określały wymiary macierzy wynikowej, która
będzie wypełniona w/g algorytmu: jeśli indeks wiersza jest większy od indeksu kolumny
wartością komórki jest indeks wiersza, w przeciwnym wypadku wartością komórki jest indeks
kolumny. Funkcja jako wynik powinna zwracać uzupełnioną macierz, jeżeli nie jest to możliwe to powinna zwrócić *None*. Na koniec wyświetlić wynikową macierz dla dowolnych argumentów $m$, $n$ z przedziału $\langle3,7\rangle$.
  
***Wskazówka:*** Inicjalizacja pustej macierz wykonywana jest w pakiecie Numpy przy pomocy funkcji  *[zeros](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.zeros.html)*, zaś macierzy składającej się z jedynek *[ones](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)*.

In [35]:
zero_matrix = np.zeros((2, 2))
ones_matrix = np.ones((3,1))

print('zero_matrix: \n{}'.format(zero_matrix))
print('ones_matrix: \n{}'.format(ones_matrix))

zero_matrix: 
[[0. 0.]
 [0. 0.]]
ones_matrix: 
[[1.]
 [1.]
 [1.]]


Rozwiązanie

In [36]:
def custom_matrix(m: int, n: int):
    """Funkcja zwraca macierz o wymiarze mxn zgodnie 
    z opisem zadania 7.  
    
    Parameters:
    m (int): ilość wierszy macierzy
    n (int): ilość kolumn macierzy  
    
    Returns:
    np.ndarray: macierz zgodna z opisem z zadania 7.
    """
    if m < 0 or n < 0:
        return None
    if not isinstance(m, int):
        return None
    if not isinstance(n, int):
        return None

    M = np.zeros((m, n))
    i, j = 0, 0

    while i < m:
        j = 0
        while j < n:
            if j > i:
                M[i][j] = j
            elif i > j:
                M[i][j] = i
            elif j == i:
                M[i][j] = j
            j = j + 1
        i = i + 1
    return M

print(custom_matrix(7, 5))

[[0. 1. 2. 3. 4.]
 [1. 1. 2. 3. 4.]
 [2. 2. 2. 3. 4.]
 [3. 3. 3. 3. 4.]
 [4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5.]
 [6. 6. 6. 6. 6.]]


***Zadanie 7.***

Biblioteka Numpy posiada własne metody, pozwalające na szybsze i wygotniejsze wykonywanie operacji na wektorach i macierzach. Kolejne zadania mają na celu przećwiczenie tych metod. Zamiast samemu implementować mnożenie macierzy, należy skorzystać właśnie z wbudowanych funkcji Numpy. Najbardzie podstawowe z nich to *[np.multiply](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.multiply.html)*, *[np.dot](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.dot.html)* oraz *[np.matmul](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.matmul.html)*. Przed wykonaniem zadania należy zapoznać się z ich dokumentacją, aby stosować poprawną funkcję do danego typu mnożenia. Dodatkowo ciekawą i użyteczną funkcjonalnością Numpy, wykorzystywaną niekiedy przy dodawaniu macierzy jest *broadcasting*, proszę o zapoznaie się z opisem:  *[[1]](https://docs.scipy.org/doc/numpy-1.15.0/user/basics.broadcasting.html)* *[[2]](https://www.tutorialspoint.com/numpy/numpy_broadcasting.htm)*.

Zainicjalizować dwa wektory $v_1$ i $v_2$:

$v_1 = \begin{bmatrix}1\\3\\13\end{bmatrix} \quad v_2 = \begin{bmatrix}8\\5\\-2\end{bmatrix}$

Następnie wykonać operacje i wypisać ich wynik:
- $4*v_1$
- $-v_2 + \begin{bmatrix}2\\2\\2\end{bmatrix}$
- $v_1 \circ v_2$ (w sensie mnożenia macierzy, tzw. mnożenie macierzy w sensie Cauchy’ego)
- $v_1 * v_2$ (w sensie mnożenia Hadamarda (element-wise))

***Wskazówki:*** Warto wiedzieć o *[np.dot](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.dot.html)* i *[np.multiply](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.multiply.html)*. Zbadać jak zachowuje się przeciążony operator mnożenia $*$ oraz $@$ dla macierzy $ndarray$.

Rozwiązanie:

In [79]:
v1 = np.array([1, 3, 13]).T
v2 = np.array([8, 5, -2]).T

print('4*v1 =', np.multiply(4, v1))
print('-v2 + [2, 2, 2] =', -v2 + np.array([2, 2, 2]))
print('v1*v2 (Cauchy) =', np.dot(v1, v2))
print('v1*v2 (element-wise) =', np.multiply(v1, v2))

4*v1 = [ 4 12 52]
-v2 + [2, 2, 2] = [-6 -3  4]
v1*v2 (Cauchy) = -3
v1*v2 (element-wise) = [  8  15 -26]


***Zadanie 8.***
Zainicjalizować macierz $M_1$:

$M_1 = \begin{bmatrix}1&-7&3\\-12&3&4\\5&13&-3\end{bmatrix}$

Następnie wykonać operacje i wypisać ich wynik:
- $3M_1$
- $3M_1 + \begin{bmatrix}1&1&1\\1&1&1\\1&1&1\end{bmatrix}$
- $M_1^T$
- $M_1 \circ v_1$ 
- $v_2^T \circ M_1$

Rozwiązanie:

In [75]:
M1 = np.array([[1, -7, 3], [-12, 3, 4], [5, 13, -3]])
Mo = np.ones((3, 3))

print('M1 = \n', M1)
print('3*M1 = \n', np.multiply(3, M1))
print('3*M1 + Mo = \n', np.multiply(3, M1) + Mo)
print('3*M1 = \n', np.multiply(3, M1))
print('M1.T = \n', M1.T)
print('M1*v1 (Cauchy) = \n', np.multiply(M1, v1))
print('M1*v2 (Cauchy) = \n', np.multiply(M1, v2.T))

M1 = 
 [[  1  -7   3]
 [-12   3   4]
 [  5  13  -3]]
3*M1 = 
 [[  3 -21   9]
 [-36   9  12]
 [ 15  39  -9]]
3*M1 + Mo = 
 [[  4. -20.  10.]
 [-35.  10.  13.]
 [ 16.  40.  -8.]]
3*M1 = 
 [[  3 -21   9]
 [-36   9  12]
 [ 15  39  -9]]
M1.T = 
 [[  1 -12   5]
 [ -7   3  13]
 [  3   4  -3]]
M1*v1 (Cauchy) = 
 [[  1 -21  39]
 [-12   9  52]
 [  5  39 -39]]
M1*v2 (Cauchy) = 
 [[  8 -35  -6]
 [-96  15  -8]
 [ 40  65   6]]


Materiały uzupełniające:
- [Scipy Lecture Notes](http://www.scipy-lectures.org/index.html)
- [NumPy for Matlab users](https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html#numpy-for-matlab-users)
- [Python Tutorial - W3Schools](https://www.w3schools.com/python/default.asp)
- [NumPy](https://www.numpy.org)
- [Matplotlib](https://matplotlib.org/)
- [Anaconda](https://www.anaconda.com/)
- [Learn Python for Data Science](https://www.datacamp.com/learn-python-with-anaconda?utm_source=Anaconda_download&utm_campaign=datacamp_training&utm_medium=banner)
- [Learn Python](https://www.learnpython.org/)
- [Wujek Google](https://google.pl) i [Ciocia Wikipedia](https://pl.wikipedia.org/wiki/Wikipedia:Strona_g%C5%82%C3%B3wna)